name: test

on: 
  push:
  repository_dispatch:
  schedule:
     - cron: '05 5 1 * *' # <https://crontab.guru/#05_5_1_*_*> - "At 05:05 on day-of-month 1"  

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup Perl environment
      uses: shogo82148/actions-setup-perl@v1.14.2
      with: 
        install-modules-with: cpanm 
    - name: test
      run: ./run_tests.sh
        
